name: Build and upload mod
on:
  release:
    types: [ published ]
    branches:
      - '1.16-release'
      - '1.16-dev'

jobs:

  path:
    name: Generate file path
    runs-on: ubuntu-latest
    outputs:
      file_path: ${{steps.file.outputs.file_path}}
      mod_name: ${{steps.file.outputs.mod_name}}
      mod_version: ${{steps.file.outputs.mod_version}}
      mc_patch_version: ${{steps.file.outputs.mc_patch_version}}
      mc_minor_version: ${{steps.file.outputs.mc_minor_version}}
      java_version: ${{steps.file.outputs.java_version}}
    steps:
      - name: Get Mod Name
        id: file
        run: echo "::set-output name=mod_name::$(cat build.gradle | sed -n 'archivesBaseName \= //p' | tr -d "'")"
      - name: Get Mod Version
        id: file
        run: echo "::set-output name=mod_version::$(cat build.gradle | sed -n 's/version \= //p' | tr -d "'")"
      - name: Get Java Version
        id: file
        run: echo "::set-output name=java_version::$(cat build.gradle | grep -o -P '(?<=JavaLanguageVersion.of\().*(?=\))')"
      - name: Get MC Patch Version
        id: file
        run: echo "::set-output name=mc_patch_version::$(echo ${{steps.file.outputs.mod_version}} | awk -F- '{print $1}')"
      - name: Get MC Minor Version
        id: file
        run: echo "::set-output name=mc_minor_version::$(echo ${{steps.file.outputs.mc_patch_version}} | awk -F. '{print $1"-"$2}'"
      - name: Generate file path
        id: file
        run: echo "::set-output name=file_path::./build/libs/${{steps.file.outputs.mod_name}}-${{steps.file.outputs.mod_version}}.jar"

  build:
    name: Build and cache
    runs-on: ubuntu-latest
    needs: [ path ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '${{needs.path.outputs.java_version}}'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew :build
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{needs.path.outputs.file_path}}
          key: ${{github.sha}}

#  curseforge:
#    name: Upload to CurseForge
#    runs-on: ubuntu-latest
#    needs: [ path,build ]
#    steps:
#      - name: Restore cache
#        uses: actions/cache@v2
#        with:
#          path: ${{needs.path.outputs.file_path}}
#          key: ${{github.sha}}
#      - name: Upload to CurseForge
#        uses: itsmeow/curseforge-upload@v3
#        with:
#          token: ${{secrets.curseforge_api}}
#          project_id: 433633
#          game_endpoint: minecraft
#          file_path: ${{needs.path.outputs.file_path}}
#          changelog: ${{github.event.release.body}}
#          display_name: ${{needs.path.outputs.mod_name}}-${{needs.path.outputs.mod_version}}
#          release_type: release
#          game_versions: minecraft-${{needs.path.outputs.mc_minor_version}}:${{needs.path.outputs.mc_patch_version}},java:Java ${{needs.path.outputs.java_version}},Forge