name: Build and upload mod
on:
  release:
    types: [ published ]
    branches:
      - '1.16-release'
      - '1.16-dev'

jobs:

  path:
    name: Generate file path
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Details
        run: |
          echo "mod_name=$(cat ./build.gradle | sed -n 's/archivesBaseName \= //p' | tr -d "'")" >> $GITHUB_ENV
          echo "mod_version=$(cat ./build.gradle | sed -n 's/version \= //p' | tr -d "'")" >> $GITHUB_ENV
          echo "java_version=$(cat ./build.gradle | grep -o -P '(?<=JavaLanguageVersion.of\().*(?=\))')" >> $GITHUB_ENV
      - name: Breakdown Versions
        run: |
          echo "mc_patch_version=$(echo ${{env.mod_version}} | awk -F- '{print $1}')" >> $GITHUB_ENV
          echo "mc_minor_version=$(echo ${{env.mc_patch_version}} | awk -F. '{print $1"-"$2}')" >> $GITHUB_ENV
      - name: Get Details
        run: echo "file_path=./build/libs/${{env.mod_name}}-${{env.mod_version}}.jar" >> $GITHUB_ENV

  build:
    name: Build and cache
    runs-on: ubuntu-latest
    needs: [ path ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '${{env.java_version}}'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew :build
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{needs.path.outputs.file_path}}
          key: ${{github.sha}}

#  curseforge:
#    name: Upload to CurseForge
#    runs-on: ubuntu-latest
#    needs: [ path,build ]
#    steps:
#      - name: Restore cache
#        uses: actions/cache@v2
#        with:
#          path: ${{env.file_path}}
#          key: ${{github.sha}}
#      - name: Upload to CurseForge
#        uses: itsmeow/curseforge-upload@v3
#        with:
#          token: ${{secrets.curseforge_api}}
#          project_id: 433633
#          game_endpoint: minecraft
#          file_path: ${{env.file_path}}
#          changelog: ${{github.event.release.body}}
#          display_name: ${{env.mod_name}}-${{env.mod_version}}
#          release_type: release
#          game_versions: minecraft-${{env.mc_minor_version}}:${{env.mc_patch_version}},java:Java ${{env.java_version}},Forge